apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  # Namespace where the node-base-deployment is running
  name: prometheus-role
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]