apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-role-binding
  namespace: default  # Namespace where the role is applied
subjects:
  - kind: ServiceAccount
    name: prometheus  # Replace with the name of your Prometheus service account
    namespace: monitoring  # Namespace where the service account exists
roleRef:
  kind: Role
  name: prometheus-role
  apiGroup: rbac.authorization.k8s.io