apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-node-base-deployment
  namespace: monitoring 
  labels:
    release: prometheus
    
spec:
  endpoints:
    - port: web
      interval: 15s 
      path: /metrics  
      scheme: http
#  jobLabel: stack
  namespaceSelector:
    matchNames:
      - default
  selector: 
    matchLabels:
      app: node-base-deployment
  
